### ISSUE TITLE
[feat] 홈 뷰 서버 연결

### ISSUE THREAD

**Issue by YuBeen-Park** [Team-KeepGoEat/KeepGoEat-AOS#68]
## What is this issue? 🛠
홈 뷰 서버 연결
## Progress 🏃‍♀️
- [x] 홈 - 홈 화면조회 api
- [x] 홈 - 목표 달성 api

**Comment by youngjinc** [comment]
@YuBeen-Park 목표 달성 api 연동 완료 시 해당 이슈도 닫아주세용!
