### ISSUE TITLE
[feat] 온보딩에 로티 추가하기

### ISSUE THREAD

**Issue by Dan2dani** [Team-KeepGoEat/KeepGoEat-AOS#71]
## What is this issue? 🛠
온보딩 뷰에 로티 애니메이션을 추가합니다.
## Progress 🏃‍♀️
- [ ] 로티 애니메이션을 추가합니다.

**Comment by youngjinc** [comment]
로티에서 텍스트가 깨지는 이슈로 png로 대체하기로 결정
